<a href="https://colab.research.google.com/github/vakitideekshareddy-star/ACE-BOOTCAMP-JUN-2026/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
print(np.__version__)
arr1=np.array([[[1,2,3,4],[2,4,6,3],[5,6,7,8]],
               [[1,2,3,4],[2,4,6,3],[5,6,7,8]],
               [[1,2,3,4],[2,4,6,3],[5,6,7,8]]])
print(arr1)
#To check Dimensions of an array in Numpy
print(arr1.ndim)
print(arr1.shape)
print(arr1[2,2,3])
print(arr1[2][1][3])

2.0.2
[[[1 2 3 4]
  [2 4 6 3]
  [5 6 7 8]]

 [[1 2 3 4]
  [2 4 6 3]
  [5 6 7 8]]

 [[1 2 3 4]
  [2 4 6 3]
  [5 6 7 8]]]
3
(3, 3, 4)
8
3


Slice


In [47]:
import numpy as np

arr=np.array([[1,2,3,4],
              [1,12,3,4]])
print(arr[:,2:4])

[[3 4]
 [3 4]]


Arithmetic (Operators and Functions)
Scalar Arthmetics (Operations perform using a single value

In [62]:
import numpy as np
arr = np.array([[1,4,5,8,9],[1,64,25,18,9],[18,4,56,8,29]])
arr1 = np.array([2,8,10,16,18])

print("Multiplication:",arr*2)
print("Addition:",arr+5)
print(np.add(2,arr1))#Scalar Arthmetic Function
print("Subtraction:",arr-1)
print("Division:",arr/2)
print(np.divide(2,arr1))#Scalar Arthmetic Function
print("Modulus:",arr%2)
print("Power:",arr**2)
print(arr//2)


#Vector Arthmetic
print(np.sum(arr))
print(np.sum(arr1))


print("Actual Array:\n",arr)
print("Sum of the Elements using vector:\n",np.sum(arr,0))


Multiplication: [[  2   8  10  16  18]
 [  2 128  50  36  18]
 [ 36   8 112  16  58]]
Addition: [[ 6  9 10 13 14]
 [ 6 69 30 23 14]
 [23  9 61 13 34]]
[ 4 10 12 18 20]
Subtraction: [[ 0  3  4  7  8]
 [ 0 63 24 17  8]
 [17  3 55  7 28]]
Division: [[ 0.5  2.   2.5  4.   4.5]
 [ 0.5 32.  12.5  9.   4.5]
 [ 9.   2.  28.   4.  14.5]]
[1.         0.25       0.2        0.125      0.11111111]
Modulus: [[1 0 1 0 1]
 [1 0 1 0 1]
 [0 0 0 0 1]]
Power: [[   1   16   25   64   81]
 [   1 4096  625  324   81]
 [ 324   16 3136   64  841]]
[[ 0  2  2  4  4]
 [ 0 32 12  9  4]
 [ 9  2 28  4 14]]
259
54
Actual Array:
 [[ 1  4  5  8  9]
 [ 1 64 25 18  9]
 [18  4 56  8 29]]
Sum of the Elements using vector:
 [20 72 86 34 47]


In [1]:
import numpy as np

arr=np.array([
    [1,2],
    [3,4]
])
arr1=np.array([
    [1,2],
    [3,4]
])
arr1.flags.writeable = False #read only
print(arr1)
#arr1[0,0]=100
print("Multiplication:\n",arr @ arr1)
print("Multiplication:\n",np.matmul(arr,arr1))
print("Addition:\n",arr+arr1)
print("Subtraction:\n",arr-arr1)
print("Division:\n",arr/arr1)
print("Modulus:\n",arr%arr1)
print("Power:\n",arr**arr1)
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))


[[1 2]
 [3 4]]
Multiplication:
 [[ 7 10]
 [15 22]]
Multiplication:
 [[ 7 10]
 [15 22]]
Addition:
 [[2 4]
 [6 8]]
Subtraction:
 [[0 0]
 [0 0]]
Division:
 [[1. 1.]
 [1. 1.]]
Modulus:
 [[0 0]
 [0 0]]
Power:
 [[  1   4]
 [ 27 256]]
2.5
1.118033988749895
1.25
1
4
0
3


In [25]:
import numpy as np

marks = np.array([
                  [95,100,1,55,68],
                  [25,45,63,77,58]
                  ])
#marks.flags.writeable = False
#print(marks)
marks[(marks>=50)&(marks<=100)]= 5
print(marks)
print("Comparision:",)

[[ 5  5  1  5  5]
 [25 45  5  5  5]]
Comparision:


In [38]:
import numpy as np
arr = np.array([[1,2]])
arr1=np.array([[1,2],[1,1],[6,3],[4,5]])
print("Shaper of Arr:",arr.shape)
print("Shape of Arr1:",arr1.shape)
print(arr*arr1)

Shaper of Arr: (1, 2)
Shape of Arr1: (4, 2)
[[ 1  4]
 [ 1  2]
 [ 6  6]
 [ 4 10]]


In [82]:
#%%writefile shuffle_demo.py
import numpy as np
ran = np.random.default_rng()
print(ran.integers(10))
print(ran.uniform(low=10,high=90,size=10))
1

arr=np.array(["HP","Dell","Toshiba","MacAir","Lenova"])
ran.shuffle(arr)
print(arr)

print(ran.choice(arr))

0
[47.56171465 82.17318768 77.18439553 69.5132509  61.33607383 47.32379164
 21.77676107 82.44774203 51.48610086 79.74340002]
['HP' 'Lenova' 'Dell' 'Toshiba' 'MacAir']
Dell
